"""Dump CREATE TABLE / CREATE INDEX DDL for every model in Base.metadata.

Uses a transient in-memory SQLite engine via SQLAlchemy's reflection
loop. The DDL is dialect-aware: pass --dialect=postgresql for the
default postgres DDL we'd ship to production.

This script's output is the source-of-truth for the
000_create_base_schema migration. After adding a new model, regenerate
the migration's body by piping this script's stdout into the file.

Usage:
    python scripts/inspect_model_ddl.py > /tmp/ddl.sql
"""
import sys
from sqlalchemy import create_engine
from sqlalchemy.schema import CreateTable, CreateIndex

from app.models import Base


def main() -> None:
    dialect = "postgresql"
    engine = create_engine(f"{dialect}://", strategy="mock", executor=lambda *a, **kw: None)
    out = sys.stdout
    out.write("-- AUTOGENERATED from Base.metadata — DO NOT EDIT\n")
    out.write("-- Run scripts/inspect_model_ddl.py to regenerate.\n")
    for table in sorted(Base.metadata.tables.values(), key=lambda t: t.name):
        out.write("\n")
        out.write(f"-- table: {table.name}\n")
        out.write(str(CreateTable(table).compile(engine)))
        out.write(";\n")
        for ix in table.indexes:
            out.write(str(CreateIndex(ix).compile(engine)))
            out.write(";\n")


if __name__ == "__main__":
    main()