"""Reusable PDF generation helpers for study materials.

Provides a single public helper, ``material_to_pdf``, that accepts raw
study text + parsed metadata and returns a branded PDF as ``bytes``.
The implementation is intentionally decoupled from the HTTP layer so
it can be reused from routers, Celery tasks, or admin scripts without
any request-context dependency.
"""

from __future__ import annotations

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

# ---------------------------------------------------------------------------
# Brand palette
# ---------------------------------------------------------------------------
MINT = colors.HexColor("#0E7C66")
MINT_SOFT = colors.HexColor("#E6F5F1")
INK = colors.HexColor("#1A1A1A")
INK_MUTED = colors.HexColor("#666666")
BORDER = colors.HexColor("#D9D9D9")


# ---------------------------------------------------------------------------
# Public helper
# ---------------------------------------------------------------------------

def material_to_pdf(
    title: str,
    content: str,
    *,
    exam_type: str | None = None,
    topic_names: list[str] | None = None,
    asset_count: int = 0,
    created_at: datetime | None = None,
    source_label: str = "PagePay Study",
) -> bytes:
    """Render a study material as a branded PDF.

    Args:
        title: Material title.
        content: Extracted raw text from the SOW.
        exam_type: Optional exam tag, e.g. ``"JAMB"``.
        topic_names: Optional list of AI-parsed topic names.
        asset_count: Number of generated study assets.
        created_at: Optional upload timestamp.
        source_label: Brand string shown in the footer.

    Returns:
        Raw PDF bytes suitable for ``StreamingResponse`` output or
        ``expo-sharing`` on the client.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    styles = _build_styles()
    story: list = []

    # ── Cover / header ────────────────────────────────────────────────────
    story.append(Paragraph(f"<b>{_escape(title)}</b>", styles["title"]))
    story.append(Spacer(1, 6))

    meta_items: list[str] = []
    if exam_type:
        meta_items.append(f"<b>Exam:</b> {_escape(exam_type.upper())}")
    if created_at:
        meta_items.append(f"<b>Date:</b> {created_at.strftime('%d %b %Y')}")
    if topic_names:
        meta_items.append(f"<b>Topics:</b> {len(topic_names)}")
    if asset_count:
        meta_items.append(f"<b>Assets:</b> {asset_count}")

    if meta_items:
        meta_text = " &nbsp;&nbsp;|&nbsp;&nbsp; ".join(meta_items)
        story.append(Paragraph(meta_text, styles["meta"]))
        story.append(Spacer(1, 10))

    story.append(Spacer(1, 2))
    story.append(_divider())
    story.append(Spacer(1, 14))

    # ── Topic outline ─────────────────────────────────────────────────────
    if topic_names:
        story.append(Paragraph("<b>Topics Covered</b>", styles["heading"]))
        for idx, name in enumerate(topic_names, 1):
            story.append(
                Paragraph(
                    f"{idx}. {_escape(name)}",
                    styles["body"],
                )
            )
        story.append(Spacer(1, 14))
        story.append(_divider())
        story.append(Spacer(1, 14))

    # ── Body content ──────────────────────────────────────────────────────
    story.append(Paragraph("<b>Content</b>", styles["heading"]))
    story.append(Spacer(1, 6))

    paragraphs = _split_paragraphs(content or "")
    for para in paragraphs:
        text = _escape(para)
        if not text:
            story.append(Spacer(1, 8))
            continue
        story.append(Paragraph(text, styles["body"]))
        story.append(Spacer(1, 4))

    # ── Footer note ───────────────────────────────────────────────────────
    story.append(Spacer(1, 18))
    story.append(_divider())
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            f"Generated by {_escape(source_label)} · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["footer"],
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_styles() -> dict[str, ParagraphStyle]:
    base = ParagraphStyle
    return {
        "title": base(
            "MaterialTitle",
            fontSize=20,
            leading=26,
            textColor=MINT,
            alignment=TA_LEFT,
            spaceAfter=4,
        ),
        "meta": base(
            "MaterialMeta",
            fontSize=9,
            leading=14,
            textColor=INK_MUTED,
            alignment=TA_LEFT,
        ),
        "heading": base(
            "MaterialHeading",
            fontSize=13,
            leading=18,
            textColor=MINT,
            spaceAfter=6,
        ),
        "body": base(
            "MaterialBody",
            fontSize=11,
            leading=17,
            textColor=INK,
            alignment=TA_JUSTIFY,
        ),
        "footer": base(
            "MaterialFooter",
            fontSize=8,
            leading=12,
            textColor=INK_MUTED,
            alignment=TA_CENTER,
        ),
    }


def _divider() -> Table:
    return Table(
        [[""]],
        colWidths=[6.5 * inch],
        style=TableStyle(
            [
                ("LINEBELOW", (0, 0), (-1, 0), 1, BORDER),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        ),
    )


def _escape(text: str) -> str:
    """Minimal XML escaping for ReportLab Paragraph markup."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _split_paragraphs(text: str) -> list[str]:
    """Split on blank lines; preserve paragraph boundaries."""
    parts = text.split("\n\n")
    return [p.strip() for p in parts if p.strip()]
